# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1

In [7]:
import numpy as np
x= np.arange(1,11,1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [6]:
v= np.array([[0,0,0],[0,0,0],[0,0,0]])
print (v)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
v=np.zeros

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3

In [10]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [16]:
z=np.linspace(0,5,10)
print(z)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4

In [17]:
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5

In [31]:

m= np.random.random([4,4])
m

array([[0.32764023, 0.72636008, 0.31035279, 0.02082162],
       [0.9747926 , 0.88937193, 0.36601086, 0.87864157],
       [0.17363126, 0.94171936, 0.72923976, 0.22865743],
       [0.19813074, 0.91668969, 0.71788666, 0.71788163]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6

In [33]:
m.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7

In [43]:
b=np.random.randint(15,size=16)
print(b)
print(b.shape)
b.shape=(4,4)
print(b)

[ 8  3  1 14 14 12 11  4  6 10  0  7  0  5  8  9]
(16,)
[[ 8  3  1 14]
 [14 12 11  4]
 [ 6 10  0  7]
 [ 0  5  8  9]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8

In [44]:
print(b.dtype)



int64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9

In [52]:
f=np.arange(1,101)
f[f%2==0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [56]:
g=np.random.randint(10,50,[6,6])
print(g)

array([[27, 12, 11, 39, 40, 26],
       [49, 33, 26, 14, 20, 24],
       [43, 25, 45, 16, 18, 16],
       [44, 12, 16, 19, 45, 43],
       [46, 47, 18, 16, 26, 10],
       [33, 31, 48, 30, 14, 26]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11

In [59]:

b=g[3:5 , 3:5]
print(b)


[[19 45]
 [16 26]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [61]:
somme=np.sum(g)
somme

1008

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [62]:
moy=np.mean(g)
print(moy)

28.0


In [64]:
med=np.median(g)
med

26.0

In [65]:
stndr=np.std(g)
stndr

12.492219800962339

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14

In [69]:
mx=np.max(g)
mx

49

In [70]:
mn=np.min(g)
mn

10

In [68]:
help(np.maximum)

Help on ufunc:

maximum = <ufunc 'maximum'>
    maximum(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Element-wise maximum of array elements.

    Compare two arrays and return a new array containing the element-wise
    maxima. If one of the elements being compared is a NaN, then that
    element is returned. If both elements are NaNs then the first is
    returned. The latter distinction is important for complex NaNs, which
    are defined as at least one of the real or imaginary parts being a NaN.
    The net effect is that NaNs are propagated.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays holding the elements to be compared.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it 

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15

In [84]:
r=np.random.randint(25,size=20)
print(r)
np.argmax(r)

[12 20  9 23 22  4  7  3 24 17 11  5 21 14 11 15 23  5 10  8]


8

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [91]:
e=np.random.randint(23,size=6)
print(e)
r=np.flip(e)
r

[20  6 10 14 17 12]


array([12, 17, 14, 10,  6, 20])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17

In [99]:
matr1=np.random.randint(12,size=(3,3))
matr2=np.random.randint(12,size=(3,3))
print('A :\N', matr1)
print(matr2)
mult=matr1*matr2
print (mult)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: malformed \N character escape (1359878239.py, line 3)

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [101]:
giv=np.random.randint(12,size=5)
print(giv)
diag=np.diag(giv)
print(diag)

[ 7  1  3  5 10]
[[ 7  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0 10]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
`

In [104]:
matr1=np.random.randint(12,size=(5,5))
matr2=np.random.randint(12,size=(5,5))
perf_mult=matr1*matr2
print(matr1)
print(matr2)
print(perf_mult)

[[ 8 11  9  6  3]
 [11  0  6  4  3]
 [ 1  7  4  1  5]
 [11  9  4 10 10]
 [ 8  4 11  3  9]]
[[ 8  6  9  9  2]
 [ 9  1  2  1  1]
 [ 3  5  6  3  9]
 [10  9  6  0  5]
 [ 8  0  9  6  7]]
[[ 64  66  81  54   6]
 [ 99   0  12   4   3]
 [  3  35  24   3  45]
 [110  81  24   0  50]
 [ 64   0  99  18  63]]


--

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20

In [105]:
T=np.random.randint(12,size=(3,3))
F=np.concatenate(T)
print('F is : \n' , F)

F is : 
 [ 5 10  0  2  0  5  9  1  4]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
`

In [107]:
P=np.random.randint(10, size=15)
J=np.random.randint(10, size=15)
stac_ver=np.vstack((P, J))
print('P :\n' , P)
print('J :\n' , J)
print("The array stacked is :\n", stac_ver)

P :
 [9 9 2 1 3 6 5 7 7 5 7 4 1 3 5]
J :
 [8 7 9 9 8 2 9 8 5 1 6 5 6 4 9]
The array stacked is :
 [[9 9 2 1 3 6 5 7 7 5 7 4 1 3 5]
 [8 7 9 9 8 2 9 8 5 1 6 5 6 4 9]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
`

In [108]:

P=np.random.randint(10, size=15)
J=np.random.randint(10, size=15)
stac_hor=np.hstack((P, J))
print('P :\n' , P)
print('J :\n' , J)
print("The array stacked is :\n", stac_hor)

P :
 [6 0 2 2 6 3 7 6 3 7 9 2 5 5 0]
J :
 [0 5 0 4 7 5 4 1 9 3 9 6 0 5 3]
The array stacked is :
 [6 0 2 2 6 3 7 6 3 7 9 2 5 5 0 0 5 0 4 7 5 4 1 9 3 9 6 0 5 3]


--

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23

In [112]:
M1=np.random.randint(10, size=(4,5))
M2=np.split(M1,2)
print('The given matrix : \n', M1)
print('The submatrices  : \n', M2)


The given matrix : 
 [[0 7 9 5 6]
 [1 8 7 1 1]
 [6 5 9 8 1]
 [4 2 3 0 9]]
The submatrices  : 
 [array([[0, 7, 9, 5, 6],
       [1, 8, 7, 1, 1]]), array([[6, 5, 9, 8, 1],
       [4, 2, 3, 0, 9]])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24

In [114]:
P=np.random.randint(10, size=15)
H=np.random.random([4,5])
G=np.round(P, 2)
print('Fisrt : \n', P)
print('The concern : \n ', G)



Fisrt : 
 [1 8 4 7 0 9 3 0 5 2 2 3 8 2 8]
The concern : 
  [1 8 4 7 0 9 3 0 5 2 2 3 8 2 8]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [116]:
k=np.random.randint(10, size=15)
b=k[np.unique(k)]
print('Array : \n ', k)
print('Unique element : \n ', b)

Array : 
  [3 2 8 5 1 3 9 3 6 9 9 6 7 6 1]
Unique element : 
  [2 8 5 3 9 3 6 9]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26

In [120]:
m=np.random.randint(50, size=15)
print(' First matrix : \n', m)
m[m< 10]=10
print(' Final matrix : \n', m)


 First matrix : 
 [44 34 41 49 45  0  8 29 15 22 30 20 15 42 44]
 Final matrix : 
 [44 34 41 49 45 10 10 29 15 22 30 20 15 42 44]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27

In [119]:
s=np.random.randint(10, size=15)
print(' First matrix : \n', s)
b=np.cumsum(s)
print('Cumulative sum : \n ', b)



 First matrix : 
 [7 5 5 7 5 7 9 9 6 0 1 4 4 9 7]
Cumulative sum : 
  [ 7 12 17 24 29 36 45 54 60 60 61 65 69 78 85]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [123]:
matr=np.random.randint(12,size=5)
print(matr)
b=sum(matr!=0)
print('Number of non zeros elements which are in matr are : ', b)



[8 7 2 0 5]
Number of non zeros elements which are in matr are :  4


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29

In [124]:
a=np.random.randint(20, size=15)
print(' First matrix : \n', a)
b=np.sort(a)
print('The sorted array  is: \n', b)


 First matrix : 
 [ 9 11 10 15 10  8  0  6  3  2  4 11 11 11  4]
The sorted array  is: 
 [ 0  2  3  4  4  6  8  9 10 10 11 11 11 11 15]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30

In [126]:
array=np.random.randint(60, size=(3,3))
print('the array is : \n', array)
sum_column=np.sum(array, axis=0)  #sum of the colums
print('The sum of each column is : ', sum_column)
sum_row=np.sum(array, axis=1)  #sum of the rows
print('The sum of each row is : ', sum_row)


the array is : 
 [[ 0 14 13]
 [18 29 36]
 [41 39  0]]
The sum of each column is :  [59 82 49]
The sum of each row is :  [27 83 80]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31

In [ ]:
array=np.random.randint(100, size=(3,3))
print('Previous array \n ', array)
mean_column=np.mean(array, axis=0)
sd_column=np.std(array, axis=0)
norm = (array-mean_column)/(sd_column)
print('Normalize matrix : \n ', norm)


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32

In [128]:
y1=np.random.randint(10, size=(5,5))
y2=np.random.randint(10, size=(5,5))
print('Matrix 1 : \n ', y1)
print('Matrix 2 : \n ', y2)
print('M1 * M2 : \n ', np.dot(y1, y2))

Matrix 1 : 
  [[1 3 8 1 9]
 [1 4 5 8 9]
 [2 8 4 4 3]
 [2 9 3 1 8]
 [1 1 5 2 3]]
Matrix 2 : 
  [[3 4 2 5 6]
 [3 0 9 0 4]
 [9 0 2 0 0]
 [1 4 5 7 3]
 [3 1 1 6 9]]
M1 * M2 : 
  [[112  17  59  66 102]
 [ 95  45  97 115 127]
 [ 79  27 107  56  83]
 [ 85  20 104  65 123]
 [ 62  15  34  37  43]]


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33

In [130]:
tr=np.random.randint(10, size=(3,3))
print('The Matrix is : \n', tr)
print('The trace is : ', np.trace(tr))

The Matrix is : 
 [[1 0 5]
 [1 4 9]
 [0 0 9]]
The trace is :  14


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34

In [132]:
row_swp=np.random.randint(10, size=(4,5))
print('Matrix : \n', row_swp)
row_swp[[0,2]]=row_swp[[2,0]]
print('the swap one is : \n', row_swp)

Matrix : 
 [[1 8 7 8 0]
 [5 2 9 8 0]
 [8 0 4 5 8]
 [4 0 2 0 8]]
the swap one is : 
 [[8 0 4 5 8]
 [5 2 9 8 0]
 [1 8 7 8 0]
 [4 0 2 0 8]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35

In [136]:
vec=np.random.randint(10, size=15)
print('Array : \n', vec)
b=vec[...,None]
b


Array : 
 [9 1 1 0 5 0 3 1 1 9 7 6 0 5 2]


array([[9],
       [1],
       [1],
       [0],
       [5],
       [0],
       [3],
       [1],
       [1],
       [9],
       [7],
       [6],
       [0],
       [5],
       [2]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36

In [138]:
D=np.random.randint(10, size=(3,3))
print('Matrix : \n', D)
det=float(np.linalg.det(D))
print('Determinant is : \n', det)


Matrix : 
 [[9 7 2]
 [5 5 7]
 [2 8 8]]
Determinant is : 
 -266.0000000000002


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37

In [139]:
eign=np.random.randint(10, size=(2,2))
b=np.linalg.eig(eign)
print('Eigen values : \n', b[0])
print('EIgen vector : \n', b[1])

Eigen values : 
 [ 7.27491722 -0.27491722]
EIgen vector : 
 [[ 0.66026926 -0.3545255 ]
 [ 0.75102896  0.93504634]]


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38

In [140]:
np.random.seed(10)
A=np.random.randint(10, size=(3,3))
B=np.random.randint(3)


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39

In [143]:
gauss_noise=np.random.normal(10,2,100)
gauss_noise

array([ 7.95810947,  9.67586195,  8.6840582 , 10.84422612, 11.24804668,
       11.00328019, 11.68286945,  6.71950003, 12.11601032,  9.81643111,
        8.55193081,  9.19907929, 10.89064917, 11.9198793 ,  7.30729232,
       14.03779875, 12.16475269,  6.42856435,  9.45532603,  9.41926322,
       13.31229433,  7.53086259,  7.88463055, 10.27682797,  9.82819991,
        9.72753898,  7.72576958, 11.27627161,  9.0167921 ,  7.50742998,
        9.24013585,  9.45748373,  7.09073098, 10.9033509 , 12.24961345,
       15.33974592, 12.6661992 ,  8.06471562,  9.49712134, 10.44132113,
        6.92127716, 11.48683541,  8.86913464, 10.01570046,  7.74641818,
       13.02763199,  8.78541103, 10.83664459, 11.9731135 ,  9.39728193,
        9.96473304, 11.1982322 ,  9.39478943,  8.50906828,  9.74295405,
       12.49598302, 12.12452028,  6.74273324, 10.22485543,  8.01699498,
       11.35759068, 10.81941363,  9.02097191,  9.98035932,  7.35963629,
       10.85148243, 10.93297175,  9.1942587 ,  9.9974558 ,  8.55

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40

In [142]:
A=np.random.randint(10, size=(4,4))
diag=np.diag(A)
print("The diagonals elements are: \n", diag)

The diagonals elements are: 
 [9 4 8 7]


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---